### ISSUE TITLE
Can I mimic package structure to build starspace r wrapper?

### ISSUE THREAD

**Issue by mrchypark** [pommedeterresautee/fastrtext#16]
I'll try to make R package using starspace from facebook.

fastrtext package is very similar to my purpose.
so if you don't mind, can i mimic your package structure make StarspaceR package?

Thanks in advance.

**Comment by pommedeterresautee** [comment]
I m currently doing it :-)

**Comment by mrchypark** [comment]
@pommedeterresautee OMG ok. i'll wait haha. I just want to study making package with cpp using Rcpp. Thanks again.

**Comment by pommedeterresautee** [comment]
Sincerly, I would not start by copying an existing package. Many tricks are already applied and you will learn very little about Rcpp and package maintenance. 
My advice would be to start a package from scratch (even a wrapper of an existing project).

**Comment by mrchypark** [comment]
I agree. I don't understand something why you create. Thank you for your advise.

**Comment by pommedeterresautee** [comment]
You mean there is something you don't understand in the source code of this package?
What is it?

**Comment by mrchypark** [comment]
of course. I don't know what s4 is. And I don't know cpp. I realized it's hard for me to try. :_(

**Comment by pommedeterresautee** [comment]
You will need to learn C++ without R first (really, there is no way otherwise).
Regarding S4, it s a way to perform OOP on R, I use it because Rcpp modules generates them. 
I think I made an error to rely on it... (lots of code to manage their behavior.

**Comment by mrchypark** [comment]
Sounds great.... I'll try to study cpp first.... I knew it necessary....

OOP is also on list of study for me. thanks again.

anyway I'm looking forward to package starspace ;)
