### ISSUE TITLE
computation with sentences instead of single words

### ISSUE THREAD

**Issue by watashiwa-toki** [pommedeterresautee/fastrtext#18]
For example, if in "get_word_distance(model, w1, w2)" w1 and w2 be n-word sentences instead of single words, does result of this command is real distance between sentences, or its working only with single words?

**Comment by pommedeterresautee** [comment]
Hi,
This function has been built for a single word only.
There are 2 ways to perform what you are asking:
- computing distance between vectors of sentences (how do you build this vector? just averaging or more complex)
- word mover distance is another option, you can check text2vec I think they have an implementation

**Comment by pommedeterresautee** [comment]
Here a commit which implements the feature https://github.com/pommedeterresautee/fastrtext/commit/80ba4b48b336c6435800cbe702e648768e19541c
The function is `get_sentence_representation`
