### ISSUE TITLE
How to quantize

### ISSUE THREAD

**Issue by alanault** [pommedeterresautee/fastrtext#21]
How do I quantize an existing model?

It's eluded to in the package intro help page, but I couldn't find any reference to it in help. According to the Fasttext page, they use a quantize function which runs against an existing model? Is this supported?

Many thanks!
Alan

**Comment by pommedeterresautee** [comment]
right now evrything doable by the command line is doable via the function [execute](https://pommedeterresautee.github.io/fastrtext/reference/execute.html).

Does it answer your question?

**Comment by alanault** [comment]
Yes! Thank you makes complete sense now - I can just do:

```
fastrtext::execute(commands = c("quantize",
                                "-input", model_file,
                                "-output", model_file,
```

Thanks for the pointer!
