### ISSUE TITLE
Convenience functions for training

### ISSUE THREAD

**Issue by olsgaard** [pommedeterresautee/fastrtext#26]
When training models, the whole `train_tmp_file_txt <- tempfile(); writeLines(text = train_to_write, con = train_tmp_file_txt)` dance can get quite tiresome and error-prone, and so I have written a few convenience functions for training supervised and unsupervised models, that also expose all possible arguments in tab-complete and documentation, when using these in RStudio or similar environment.

Is there an interest in including such functions in fastrtext? I can prepare a PR with the ones I use, or we can discuss API and I can prepare new versions

**Comment by pommedeterresautee** [comment]
Hi,
There is an interest for such function.
Would be happy to review your PR !

**Comment by pommedeterresautee** [comment]
Thanks a lot, it s now in the last version of fastrtext.
