### ISSUE TITLE
removed from cran

### ISSUE THREAD

**Issue by jwijffels** [pommedeterresautee/fastrtext#37]
```
Package ‘fastrtext’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-09-04 as check problems were not corrected in time. 
```

Are you going to get it back on CRAN?

**Comment by pommedeterresautee** [comment]
Tks for the alert. Yeah I will work on it in the coming days, they wrote me and told me I had up to 20 something September...
Sorry for the inconvenience.

**Comment by jwijffels** [comment]
no problem, just saw it par hazard as I had to install the package yesterday

**Comment by pommedeterresautee** [comment]
... took me time to find time :-) now it s back

**Comment by jwijffels** [comment]
Thanks for the effort!
